RESEARCH_QUEUE = "research"
AI_GENERATION_QUEUE = "ai_generation"
MEDIA_QUEUE = "media"
PUBLISHING_QUEUE = "publishing"
STRATEGY_QUEUE = "strategy"
MAINTENANCE_QUEUE = "maintenance"

ALL_QUEUES = (
    RESEARCH_QUEUE,
    AI_GENERATION_QUEUE,
    MEDIA_QUEUE,
    PUBLISHING_QUEUE,
    STRATEGY_QUEUE,
    MAINTENANCE_QUEUE,
)
